# Generated by Django 4.2.3 on 2023-09-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_attachment_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachment',
            new_name='img',
        ),
    ]
