# Generated by Django 4.2.4 on 2024-06-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_id_post_id_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
